name: nepse_scrap
description: A command-line application to scrap live transaction price for companies listed in NEPSE.
version: 1.0.0
homepage: https://www.sarbagyastha.com.np
author: Sarbagya Dhaubanjar <mail@sarbagyastha.com.np>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  http: ^0.12.0+2

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
